apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ga3o1tqhc-java-springboot
  janus-idp.io/tekton: ga3o1tqhc-java-springboot
  backstage.io/kubernetes-id: ga3o1tqhc-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ga3o1tqhc-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
